apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v2.0.0
  # - https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/v2.0.0/deploy/crds.yaml
  # - https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/v2.0.0/deploy/default/deploy.yaml
  - noodleblitz-iti-secret.yaml
  - gateway.yaml
  # - backend-route.yaml
  - frontend-route.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/kubernetes/service/loadBalancerIP
        value: 13.48.232.108
    target:
      kind: NginxProxy
      name: nginx-gateway-proxy-config
      namespace: nginx-gateway
  - patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: iti.noodleblitz.space
      - op: add
        path: /metadata/namespace
        value: default
    target:
      kind: HTTPRoute
  - patch: |-
      - op: add
        path: /spec/listeners/0/hostname
        value: iti.noodleblitz.space
      - op: add
        path: /spec/listeners/1/hostname
        value: iti.noodleblitz.space
      - op: add
        path: /spec/listeners/1/tls/certificateRefs/name
        value: noodleblitz-iti-tls
    target:
      kind: Gateway
